line-length = 90

[lint]
select = ["ALL"]
ignore = [
    "S",
    "RUF",
    "FA",
    "CPY",
    "PGH",
    "Q",
    "PLR2004",
    "D100",
    "D104",
    "D106",
    "D203",
    "D212",
    "UP006",
    "UP035",
    "DOC201",
    "DOC501",
    "DOC402",
    "TC006",
]
preview = true


[lint.per-file-ignores]
"tests/*" = ["ANN", "DTZ", "D"]


[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
